let P=null,profiles=loadProfiles(),active=localStorage.getItem('bh_active')||'',tab='home',query='',filter='all',selected=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>Number(n||0).toLocaleString('it-IT');
const apiBase=()=>localStorage.getItem('bh_api_base')||'';
function loadProfiles(){try{return JSON.parse(localStorage.getItem('bh_profiles')||'[]')}catch{return[]}}
function saveProfiles(){localStorage.setItem('bh_profiles',JSON.stringify(profiles))}
function portrait(b){return 'https://cdn.brawlify.com/brawlers/'+b.id+'.png'}
function owned(b){return {gadgets:b.gadgets?.length||0,stars:b.starPowers?.length||0,gears:b.gears?.length||0,hc:b.hyperCharges?.length||0}}
function readiness(b){const o=owned(b);return Math.min(100,Math.round((b.power||1)*5+Math.min(o.gadgets,2)*5+Math.min(o.stars,2)*5+Math.min(o.gears,2)*5+Math.min(o.hc,1)*8))}
function status(b){const r=readiness(b);if((b.power||0)>=11&&r>=75)return ['PLAY NOW','ok'];if((b.power||0)>=9)return ['UPGRADE TO META',''];return ['LOW POWER','miss']}
function nav(){return '<nav class="nav">'+[['home','⌂','Home'],['play','▶','Play'],['brawlers','●','Brawlers'],['upgrade','↗','Upgrade'],['meta','✦','Meta']].map(x=>'<button class="'+(tab===x[0]?'active':'')+'" onclick="setTab(\''+x[0]+'\')">'+x[1]+'<br>'+x[2]+'</button>').join('')+'</nav>'}
function shell(body){document.getElementById('app').innerHTML='<div class="app"><header class="top"><div class="brand"><div class="logo">Brawl <span>Helper</span></div><div class="sync">'+(active?'PROFILE':'NO PROFILE')+'</div></div><button class="profileBtn" onclick="profilePanel()">'+esc(active||'Profilo')+'</button></header><main class="content">'+body+'</main>'+nav()+'</div>'}
function setTab(t){tab=t;selected=null;render()}
function bcard(b){const o=owned(b),st=status(b);return '<div class="card" onclick="openB('+b.id+')"><div class="row"><img class="portrait" src="'+portrait(b)+'" onerror="this.style.opacity=.25"><div class="grow"><div class="bname">'+esc(b.name)+'</div><div class="small">Power '+b.power+' · Rank '+b.rank+' · '+fmt(b.trophies)+' 🏆</div><div class="chips"><span class="chip '+st[1]+'">'+st[0]+'</span><span class="chip">Readiness '+readiness(b)+'</span></div></div></div><div class="chips"><span class="chip '+(o.gadgets?'ok':'miss')+'">G '+o.gadgets+'/2</span><span class="chip '+(o.stars?'ok':'miss')+'">★ '+o.stars+'/2</span><span class="chip '+(o.gears?'ok':'miss')+'">Gear '+o.gears+'/2</span><span class="chip '+(o.hc?'ok':'miss')+'">HC '+o.hc+'</span></div></div>'}
function home(){let bs=[...P.brawlers].sort((a,b)=>readiness(b)-readiness(a));let upgrades=[...P.brawlers].filter(b=>(b.power||0)<11).sort((a,b)=>(b.trophies+b.power*100)-(a.trophies+a.power*100)).slice(0,5);return '<section class="hero"><div class="eyebrow">ACCOUNT</div><h1>'+esc(P.name)+'</h1><div class="tag">'+esc(P.tag)+' · livello '+P.expLevel+'</div><div class="stats"><div class="stat"><b>'+fmt(P.trophies)+'</b><span>TROFEI</span></div><div class="stat"><b>'+P.brawlers.length+'</b><span>BRAWLER</span></div><div class="stat"><b>'+fmt(P['3vs3Victories'])+'</b><span>VITTORIE 3V3</span></div></div><div class="rank"><span>Ranked · '+esc(P.rankedRankName)+'</span><b>'+fmt(P.rankedElo)+' Elo</b></div></section><section class="section"><h2>Best For You</h2>'+bs.slice(0,5).map(bcard).join('')+'</section><section class="section"><h2>Upgrade Advisor</h2>'+upgrades.map(b=>'<div class="action" onclick="openB('+b.id+')"><b>'+esc(b.name)+' · Power '+b.power+'</b><span class="small">Priorità basata sui dati del tuo account · '+fmt(b.trophies)+' trofei</span></div>').join('')+'</section>'}
function brawlers(){let bs=[...P.brawlers];if(query)bs=bs.filter(b=>b.name.toLowerCase().includes(query.toLowerCase()));if(filter==='p11')bs=bs.filter(b=>b.power>=11);if(filter==='upgrade')bs=bs.filter(b=>b.power<11);bs.sort((a,b)=>b.trophies-a.trophies);return '<section class="section"><h2>My Brawlers · '+P.brawlers.length+'</h2><input class="search" placeholder="Cerca Brawler..." value="'+esc(query)+'" oninput="query=this.value;render()"><div class="filters"><button class="'+(filter==='all'?'active':'')+'" onclick="filter=\'all\';render()">Tutti</button><button class="'+(filter==='p11'?'active':'')+'" onclick="filter=\'p11\';render()">Power 11</button><button class="'+(filter==='upgrade'?'active':'')+'" onclick="filter=\'upgrade\';render()">Da migliorare</button></div>'+bs.map(bcard).join('')+'</section>'}
function detail(){let b=P.brawlers.find(x=>x.id===selected),o=owned(b);return '<button class="back" onclick="selected=null;render()">← Torna ai Brawler</button><section class="hero"><div class="row"><img class="portrait" src="'+portrait(b)+'"><div><h1>'+esc(b.name)+'</h1><div class="muted">Power '+b.power+' · Rank '+b.rank+'</div><div class="muted">'+fmt(b.trophies)+' / '+fmt(b.highestTrophies)+' trofei</div></div></div></section><div class="grid"><div class="action"><b>Gadget</b><span class="small">'+o.gadgets+'/2 posseduti</span></div><div class="action"><b>Star Power</b><span class="small">'+o.stars+'/2 possedute</span></div><div class="action"><b>Gear</b><span class="small">'+o.gears+'/2 slot acquisiti</span></div><div class="action"><b>Hypercharge</b><span class="small">'+o.hc+' possedute</span></div></div><section class="card"><b>Build posseduta</b><div class="build"><div class="slot">GADGET<strong>'+(o.gadgets?'OWNED':'MISSING')+'</strong></div><div class="slot">STAR POWER<strong>'+(o.stars?'OWNED':'MISSING')+'</strong></div><div class="slot">GEAR 1<strong>'+(o.gears?'OWNED':'MISSING')+'</strong></div><div class="slot">GEAR 2<strong>'+((o.gears>1)?'OWNED':'MISSING')+'</strong></div><div class="slot">HYPER<strong>'+(o.hc?'OWNED':'MISSING')+'</strong></div></div></section><div class="notice">Progressione e meta restano separati. Il layer successivo collegherà modalità, mappa, build e snapshot meta.</div>'}
function play(){return '<section class="section"><h2>Play</h2><div class="notice">Seleziona una modalità. Il motore finale userà modalità + mappa + meta + tuo account per costruire una Top 5 personale.</div><div class="grid">'+['Ranked','Knockout','Gem Grab','Brawl Ball','Heist','Hot Zone'].map(m=>'<div class="action"><b>'+m+'</b><span class="small">Top 5 personalizzata →</span></div>').join('')+'</div><section class="section"><h2>Quick picks</h2>'+P.brawlers.slice().sort((a,b)=>readiness(b)-readiness(a)).slice(0,5).map(bcard).join('')+'</section></section>'}
function meta(){const names=['SPIKE','MAX','BELLE','8-BIT','RICO'];return '<section class="section"><h2>Meta</h2><div class="notice">Il meta live non viene inventato. Sarà alimentato dal backend con snapshot stagione/patch/modalità/mappa e relativa fonte.</div>'+names.map(n=>{let b=P.brawlers.find(x=>x.name===n);return b?bcard(b):''}).join('')+'</section><section class="card"><b>Meta Confidence</b><div class="small">Account: verificato · Meta live: da collegare.</div></section>'}
function profilePanel(){const rows=profiles.map(p=>'<div class="profileRow"><button onclick="activate(\''+esc(p.name)+'\')"><b>'+esc(p.name)+'</b><span>'+esc(p.tag)+(p.test?' · TEST':'')+'</span></button><button class="del" onclick="removeProfile(\''+esc(p.name)+'\')">×</button></div>').join('');document.getElementById('app').insertAdjacentHTML('beforeend','<div class="modal"><div class="modalBox"><div class="modalHead"><h2>Profili</h2><button onclick="closeModal()">×</button></div>'+rows+'<div class="profileForm"><input id="newName" placeholder="Nome profilo"><input id="newTag" placeholder="Player Tag, es. #22QYOQRGY"><button class="primary" onclick="addProfile()">Aggiungi account</button></div><div class="profileForm"><input id="apiBase" placeholder="Backend API URL (opzionale)" value="'+esc(apiBase())+'"><button onclick="saveApiBase()">Salva backend</button></div><div class="small">Il profilo BlackShark è solo per testing. In produzione ogni cliente userà il proprio Player Tag.</div><button class="close" onclick="closeModal()">Chiudi</button></div></div>')}
function closeModal(){document.querySelector('.modal')?.remove()}
function activate(name){const p=profiles.find(x=>x.name===name);if(!p)return;active=name;localStorage.setItem('bh_active',name);closeModal();loadProfile(p)}
function removeProfile(name){profiles=profiles.filter(p=>p.name!==name);saveProfiles();if(active===name){active='';localStorage.removeItem('bh_active');P=null}closeModal();render()}
async function addProfile(){const name=document.getElementById('newName').value.trim(),tag=document.getElementById('newTag').value.trim().toUpperCase();if(!name||!/^#[A-Z0-9]+$/.test(tag)){alert('Inserisci nome e Player Tag valido.');return}if(profiles.some(p=>p.name===name)){alert('Nome profilo già presente.');return}const p={name,tag,test:false};profiles.push(p);saveProfiles();active=name;localStorage.setItem('bh_active',name);closeModal();await loadProfile(p)}
function saveApiBase(){const v=document.getElementById('apiBase').value.trim().replace(/\/$/,'');if(v)localStorage.setItem('bh_api_base',v);else localStorage.removeItem('bh_api_base');closeModal()}
async function loadProfile(p){selected=null;tab='home';if(p.test){P=await fetch('data/player-response.json').then(r=>r.json());render();return}if(!apiBase()){P=null;render();document.getElementById('app').insertAdjacentHTML('beforeend','<div class="modal"><div class="modalBox"><h2>Collega account</h2><p>Il Player Tag è salvato. Per recuperare i dati reali serve il backend Brawl Helper.</p><p class="small">Configura il Backend API URL nei Profili. La chiave Supercell/Brawl Stars non deve mai essere inserita nell’app.</p><button class="close" onclick="closeModal()">OK</button></div></div>');return}try{const r=await fetch(apiBase()+'/api/player/'+encodeURIComponent(p.tag.slice(1)));if(!r.ok)throw new Error('Backend HTTP '+r.status);P=await r.json();render()}catch(e){P=null;render();document.getElementById('app').insertAdjacentHTML('beforeend','<div class="modal"><div class="modalBox"><h2>Errore collegamento</h2><p>'+esc(e.message)+'</p><button class="close" onclick="closeModal()">OK</button></div></div>')}}
function openB(id){selected=id;render()}
function render(){if(!P){shell('<section class="hero"><div class="eyebrow">ACCOUNT</div><h1>Nessun profilo attivo</h1><p class="muted">Apri Profili e aggiungi il tuo Player Tag. Il profilo BlackShark resta disponibile solo come ambiente di test.</p><button class="primary" onclick="profilePanel()">Gestisci profili</button></section>');return}if(selected)shell(detail());else if(tab==='home')shell(home());else if(tab==='brawlers')shell(brawlers());else if(tab==='play')shell(play());else if(tab==='upgrade')shell('<section class="section"><h2>Upgrade Advisor</h2><div class="notice">Priorità = impatto competitivo potenziale + Power + componenti mancanti + efficienza dell’investimento.</div>'+P.brawlers.filter(b=>b.power<11).sort((a,b)=>b.trophies-a.trophies).slice(0,20).map(bcard).join('')+'</section>');else shell(meta())}
async function boot(){if(!profiles.length){profiles=[{name:'BlackShark TEST',tag:'#22QYOQRGY',test:true}];saveProfiles();active=profiles[0].name;localStorage.setItem('bh_active',active)}const p=profiles.find(x=>x.name===active)||profiles[0];active=p.name;localStorage.setItem('bh_active',active);await loadProfile(p);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
boot();