/* Brawl Helper UI v2 presentation layer */
(function(){
'use strict';
const E=window.esc||((v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const F=window.fmt||((n)=>Number(n||0).toLocaleString('en-US'));
const pct=v=>{const n=Number(v);return Number.isFinite(n)?n.toFixed(n%1?1:0)+'%':'—'};
const ms=(b,mode,map)=>{const m=window.metaEntry?.(b,mode,map);return {m,score:m?.score!=null?Number(m.score):null,pick:m?.pickRate!=null?Number(m.pickRate):null,win:m?.winRate!=null?Number(m.winRate):null,rank:window.metaRankOf?.(b,mode,map)||null}};
const state=(b,t,i)=>!i||String(i.id||'').startsWith('pending:')?'PENDING':window.itemStatus?.(b,t,i)||'UNKNOWN';

function slotRows(b){
 const rows=window.guideComponents?.(b)||[],e=window.buildEntry?.(b)||{};
 return rows.map(([label,type,item])=>{
  const pending=!item||String(item.id||'').startsWith('pending:');
  const s=state(b,type,item),key=type==='gadgets'?'gadget':type==='starPowers'?'starPower':type;
  const rec=type==='gears'?(e.gears||[]).some(x=>x&&item&&window.norm(x.name)===window.norm(item.name)):!!item&&!!window.bestBuildItem?.(e,key,0)&&window.norm(window.bestBuildItem(e,key,0).name)===window.norm(item.name);
  const pick=item?.pick!=null?Number(item.pick):null;
  let cls='bhSlotUnknown',badge='<span class="bhStatus bhUnknown">? UNKNOWN</span>';
  if(pending){cls='bhSlotPending';badge='<span class="bhStatus bhPending">DATA N/A</span>'}
  else if(rec&&s==='EQUIPPED'){cls='bhSlotMetaEquipped';badge='<span class="bhStatus bhMetaGood">★ META · ✓ EQUIPPED</span>'}
  else if(rec&&s==='OWNED'){cls='bhSlotMetaOwned';badge='<span class="bhStatus bhMetaOwned">★ META · OWNED</span>'}
  else if(rec&&s==='NOT OWNED'){cls='bhSlotMetaMissing';badge='<span class="bhStatus bhMetaMissing">★ META · BUY</span>'}
  else if(s==='EQUIPPED'){cls='bhSlotEquipped';badge='<span class="bhStatus bhEquipped">✓ EQUIPPED</span>'}
  else if(s==='OWNED'){cls='bhSlotOwned';badge='<span class="bhStatus bhOwned">● OWNED</span>'}
  else if(s==='NOT OWNED'){cls='bhSlotMissing';badge='<span class="bhStatus bhMissing">＋ NOT OWNED</span>'}
  return '<button class="bhBuildSlot '+cls+'" type="button" onclick="componentModalV2ById('+b.id+',\\''+type+'\\','+JSON.stringify(String(item?.id||0))+')"><div class="bhSlotIcon">'+window.compIcon(type,item,b)+'</div><div class="bhSlotText"><small>'+E(label)+'</small><b>'+E(item?.name||'Data unavailable')+'</b>'+(pick!=null?'<em>'+pct(pick)+' PICK</em>':'')+'</div>'+badge+'</button>';
 }).join('');
}
window.buildSlotRows=slotRows;

function guide(b){
 const c=window.catalogEntry?.(b)||b,p=b?.profile||window.PROFILE_STATE?.entries?.[String(b.id)]||null;
 const role=p?.identity?.class?.name||c?.class?.name||'Brawler',desc=window.cleanGuideText?.(c?.description||c?.shortDescription||p?.identity?.description||'')||'Use the current mode/map context and adapt the build to the objective.';
 const modes=[];
 for(const mode of Object.keys(window.MODES||{})){const x=window.metaEntry?.(b,mode,'Random');if(x?.score!=null)modes.push({mode,score:Number(x.score)})}
 modes.sort((a,z)=>z.score-a.score);
 const e=window.buildEntry?.(b),parts=[];if(e?.gadget?.[0]?.name)parts.push(e.gadget[0].name);if(e?.starPower?.[0]?.name)parts.push(e.starPower[0].name);if(e?.gears?.[0]?.name)parts.push(e.gears[0].name);if(e?.gears?.[1]?.name)parts.push(e.gears[1].name);
 return '<section class="bhQuickGuide card"><div class="bhSectionHead"><div><span class="bhEyebrow">QUICK GUIDE</span><h2>How to use '+E(b.name)+'</h2></div><span class="bhRole">'+E(role)+'</span></div><p>'+E(desc)+'</p><div class="bhGuideGrid"><div><span>BEST CONTEXT</span><b>'+(modes.length?modes.slice(0,3).map(x=>E(x.mode)).join(' · '):'No validated mode signal')+'</b></div><div><span>BUILD PRIORITY</span><b>'+(parts.length?E(parts.join(' · ')):'No validated build')+'</b></div></div><div class="bhTips"><div><b>Use the selected map as context</b><span>Meta, pick rate and build signals should be read together with the current mode/map.</span></div><div><b>Separate recommendation from ownership</b><span>★ META is the statistical recommendation; ✓ EQUIPPED is your account state.</span></div></div></section>';
}

function detailV2(){
 const b=(window.P?.brawlers||[]).find(x=>x&&x.id===window.selected)||window.allBrawlers?.().find(x=>x&&x.id===window.selected);if(!b)return '';
 const owned=window.isOwnedAccount?.(b),actions=window.nextActions?.(b)||[],m=window.metaEntry?.(b,window.playMode,window.playMap),s=ms(b,window.playMode,window.playMap),buffs=window.buffieRows?.(b)||[],build=window.guideComponents?.(b)||[];
 const aligned=build.filter(([l,t,i])=>i&&!String(i.id||'').startsWith('pending:')).length;
 const bhtml=buffs.slice(0,3).map(([label,key,items,own])=>'<button class="bhBuffie '+(own===true?'bhBuffOwned':items.length?'bhBuffAvailable':'bhBuffMissing')+'" onclick="componentModalV2ById('+b.id+',\\'buffies\\',\\''+key+'\\')" type="button"><span class="bhBuffIcon">'+(own===true?'✓':items.length?'•':'×')+'</span><span><b>'+E(label)+'</b><small>'+E(own===true?'UNLOCKED':items.length?'AVAILABLE · OWNERSHIP UNKNOWN':'DATA NOT AVAILABLE')+'</small></span></button>').join('');
 const tabs=['General',...Object.keys(window.MODES||{}).slice(0,6)].map(x=>'<button class="'+((window.playMode===x)?'active':'')+'" onclick="playMode=\\''+x+'\\';playMap=\\'Random\\';render()">'+E(x)+'</button>').join('');
 return '<button class="back" onclick="selected=null;render()">← Back to Brawlers</button>'+
 '<section class="bhHero"><div class="bhHeroIdentity"><img class="bhHeroPortrait" src="'+window.portrait(b)+'" onerror="imgFallback(this,'+JSON.stringify(b.name)+')"><div class="grow"><span class="bhEyebrow">BRAWLER</span><h1>'+E(b.name)+'</h1><p>'+(owned?'Power '+b.power+' · '+F(b.trophies)+' trophies':'Not owned')+'</p></div></div><div class="bhHeroMeta">'+(s.rank?'<span class="bhTier">META #'+s.rank+'</span>':'<span class="bhTier bhMuted">META N/A</span>')+(s.score!=null?'<span>Score '+Math.round(s.score)+'</span>':'')+(s.pick!=null?'<span>'+pct(s.pick)+' pick</span>':'')+(s.win!=null?'<span>'+pct(s.win)+' win</span>':'')+'</div></section>'+
 '<section class="bhBuildCard card"><div class="bhSectionHead"><div><span class="bhEyebrow">RECOMMENDED LOADOUT</span><h2>Meta Build</h2></div><span class="bhBuildMatch">'+(aligned>=4?'✓ FULL META MATCH':aligned+' / 4 ALIGNED')+'</span></div><p class="bhExplain">★ META = current community/statistical recommendation. ✓ EQUIPPED = reported by your profile.</p><div class="bhBuildGrid">'+slotRows(b)+'</div><div class="bhLegend"><span><i class="bhLegendMeta"></i> Meta</span><span><i class="bhLegendGood"></i> Meta + Equipped</span><span><i class="bhLegendOwn"></i> Owned</span><span><i class="bhLegendMissing"></i> Not owned</span><span><i class="bhLegendUnknown"></i> Unknown</span></div></section>'+
 '<section class="bhStats card"><div class="bhSectionHead"><div><span class="bhEyebrow">ACCOUNT STATUS</span><h2>Your configuration</h2></div></div><div class="bhStatGrid"><div><b>'+aligned+'/4</b><span>BUILD ALIGNED</span></div><div><b>'+actions.filter(a=>['BUY','EQUIP','POWER'].includes(a.type)).length+'</b><span>ACTIONS</span></div><div><b>'+(s.pick!=null?pct(s.pick):'—')+'</b><span>META PICK</span></div><div><b>'+(s.win!=null?pct(s.win):'—')+'</b><span>META WIN</span></div></div></section>'+
 '<section class="card"><div class="bhSectionHead"><div><span class="bhEyebrow">META CONTEXT</span><h2>Mode & map</h2></div><span class="bhContextScore">'+(m?.score!=null?'Score '+Math.round(m.score):'No score')+'</span></div><div class="bhModeTabs">'+tabs+'</div><select class="search" onchange="playMap=this.value;render()"><option value="Random">Random / overall</option>'+((window.MODES?.[window.playMode]||[]).map(x=>'<option '+(window.playMap===x?'selected':'')+'>'+E(x)+'</option>').join(''))+'</select><div class="bhMetaNumbers"><span><b>'+(m?.pickRate!=null?pct(m.pickRate):'—')+'</b> pick</span><span><b>'+(m?.winRate!=null?pct(m.winRate):'—')+'</b> win</span><span><b>'+(m?.confidence?E(m.confidence):'—')+'</b> confidence</span></div></section>'+
 guide(b)+
 '<section class="card"><div class="bhSectionHead"><div><span class="bhEyebrow">FUNCTIONAL UPGRADES</span><h2>Buffies</h2></div><span class="small">tap for details</span></div><div class="bhBuffGrid">'+bhtml+'</div></section>'+
 '<section class="card"><div class="bhSectionHead"><div><span class="bhEyebrow">PERSONALIZED</span><h2>Next actions</h2></div></div>'+(actions.length?actions.slice(0,4).map(a=>'<div class="bhActionRow"><span class="bhActionIcon">'+(a.type==='BUY'?'＋':a.type==='EQUIP'?'✓':a.type==='POWER'?'↑':'?')+'</span><span><b>'+E(a.label)+'</b><small>'+E(a.reason)+'</small></span></div>').join(''):'<div class="bhEmpty"><b>Nothing urgent.</b><span>Your build is aligned or ownership data is incomplete.</span></div>')+'</section>'+
 '<details class="card compactDetails"><summary>Game information & all available components</summary>'+window.brawlerDefinition(b)+'</details>'+
 '<section class="card bhData"><div class="bhSectionHead"><div><span class="bhEyebrow">DATA</span><h2>Freshness</h2></div></div><p>Meta/build: '+E(window.BUILD_STATE?.updatedAt||'—')+' · Components: '+E(window.COMPONENT_STATE?.generatedAt||'—')+'</p></section>';
}
window.detail=detailV2;

function bcardV2(b,compact=false,mode=window.playMode,map=window.playMap,rank=null,kind=''){
 if(!b)return '';
 const m=window.metaEntry?.(b,mode,map),r=rank||window.metaRankOf?.(b,mode,map),own=window.isOwnedAccount?.(b),build=window.guideComponents?.(b)||[];
 const aligned=build.filter(x=>x[2]&&!String(x[2].id||'').startsWith('pending:')).length;
 return '<div class="bhBrawlerCard" onclick="openB('+b.id+')"><div class="bhRank">'+(r?'#'+r:'•')+'</div><img class="bhCardPortrait" src="'+window.portrait(b)+'" onerror="imgFallback(this,'+JSON.stringify(b.name)+')"><div class="bhCardMain"><div class="bhCardTop"><b>'+E(b.name)+'</b><span class="bhPower">'+(own?'P'+b.power:'NOT OWNED')+'</span></div><div class="bhCardSub">'+(own?F(b.trophies)+' trophies':'')+' · '+(m?'META':'META N/A')+'</div><div class="bhMetricRow"><span><b>'+(m?.score!=null?Math.round(m.score):'—')+'</b><small>META</small></span><span><b>'+(m?.pickRate!=null?pct(m.pickRate):'—')+'</b><small>PICK</small></span><span><b>'+(m?.winRate!=null?pct(m.winRate):'—')+'</b><small>WIN</small></span><span><b>'+aligned+'/5</b><small>BUILD</small></span></div></div></div>';
}
window.bcard=bcardV2;

function homeV2(){
 const owned=[...(window.P?.brawlers||[])].filter(Boolean),ranked=window.globalRankList?.()||[],best=ranked.filter(x=>window.isOwnedAccount?.(x.b)).slice(0,3),plans=owned.map(b=>({b,plan:window.upgradePriority?.(b)})).filter(x=>x.plan?.actions?.some(a=>['BUY','POWER','EQUIP'].includes(a.type))).sort((a,z)=>(z.plan.score||0)-(a.plan.score||0)).slice(0,3),sync=window.profileStatus||'OFFLINE';
 return '<section class="bhHomeHero"><div><span class="bhEyebrow">ACCOUNT DASHBOARD</span><h1>'+E(window.P.name)+'</h1><p>'+E(window.P.tag)+' · Profile '+E(sync)+'</p></div><div class="bhHomeStats"><div><b>'+F(window.P.trophies)+'</b><span>TROPHIES</span></div><div><b>'+F(owned.length)+'</b><span>BRAWLERS</span></div><div><b>'+F(window.P['3vs3Victories'])+'</b><span>3V3 WINS</span></div></div></section>'+
 '<section class="bhQuickActions"><button onclick="setTab(\\'brawlers\\')"><b>Brawlers</b><span>Builds & status</span></button><button onclick="setTab(\\'play\\')"><b>Meta</b><span>Modes & maps</span></button><button onclick="setTab(\\'upgrade\\')"><b>Upgrade</b><span>Next actions</span></button></section>'+
 '<section class="section"><div class="bhSectionHead"><div><span class="bhEyebrow">ACCOUNT-SPECIFIC</span><h2>What needs attention</h2></div><span class="small">'+(plans.length?plans.length+' actions':'All clear')+'</span></div>'+(plans.length?plans.map((x,i)=>window.upgradeCard(x,i+1)).join(''):'<div class="bhEmpty card"><b>No confirmed upgrade action.</b><span>Open a Brawler to confirm ownership when the API cannot expose it.</span></div>')+'</section>'+
 '<section class="section"><div class="bhSectionHead"><div><span class="bhEyebrow">CURRENT META</span><h2>Best options you own</h2></div><span class="small">overall meta</span></div>'+(best.length?best.map((x,i)=>bcardV2(x.b,true,'General','Random',x.meta?.rank||i+1,'ownedTop')).join(''):'<div class="bhEmpty card"><b>No validated meta available.</b><span>The synchronized meta snapshot is required here.</span></div>')+'</section>'+
 '<section class="card bhHomeData"><div class="bhSectionHead"><div><span class="bhEyebrow">SYNC</span><h2>Data status</h2></div><span class="bhSyncDot">● '+E(sync)+'</span></div><div class="bhDataGrid"><span>Meta <b>'+(window.META_STATE?.loaded?'READY':'PENDING')+'</b></span><span>Builds <b>'+(window.BUILD_STATE?.loaded?'READY':'PENDING')+'</b></span><span>Components <b>'+F(window.CATALOG_STATE?.count||0)+'</b></span><span>Overdrive <b>'+((window.COMPONENT_STATE?.entries&&Object.values(window.COMPONENT_STATE.entries).some(x=>x?.overdrives?.length))?'READY':'DATA N/A')+'</b></span></div></section>';
}
window.home=homeV2;

const css=String.raw\`
.bhEyebrow{display:block;font-size:9px;letter-spacing:1.5px;font-weight:950;color:#9eb0cb}.bhSectionHead{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:9px}.bhSectionHead h2{margin:2px 0 0;font-size:19px}.bhRole,.bhBuildMatch,.bhContextScore{font-size:9px;font-weight:950;padding:7px 9px;border-radius:999px;border:1px solid #405274;background:#18243a;color:#aebbd0}.bhBuildMatch{color:#9ff0c6;border-color:#3f8067;background:rgba(97,230,167,.08)}
.bhHero{margin:12px 0;background:radial-gradient(circle at 90% 15%,rgba(255,211,78,.12),transparent 32%),linear-gradient(145deg,#16243c,#0e1729);border:1px solid #3b5377;border-radius:24px;padding:18px;box-shadow:0 16px 45px rgba(0,0,0,.25)}.bhHeroIdentity{display:flex;align-items:center;gap:13px}.bhHeroPortrait{width:82px;height:82px;border-radius:22px;object-fit:contain;background:#162238;border:1px solid #415b82}.bhHero h1{font-size:34px;margin:2px 0}.bhHero p{margin:3px 0;color:#9eacc1}.bhHeroMeta{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.bhHeroMeta span{font-size:10px;font-weight:850;color:#b4c0d3;border:1px solid #354b6c;background:#162238;padding:6px 8px;border-radius:9px}.bhHeroMeta .bhTier{color:#ffd95b;border-color:#66572b;background:rgba(255,211,78,.08)}
.bhBuildCard{background:linear-gradient(145deg,#141f34,#101a2b);border-color:#3b5377}.bhExplain{font-size:10px;line-height:1.45;color:#8fa0b9;margin:0 0 10px}.bhBuildGrid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;overflow-x:auto;padding-bottom:2px}.bhBuildSlot{min-width:0;min-height:142px;border:1px solid #334765;border-radius:14px;background:#16243a;color:#fff;padding:8px 5px;display:flex;flex-direction:column;align-items:center;gap:5px;text-align:center}.bhBuildSlot:hover{border-color:#667fa9}.bhSlotIcon{height:38px;display:flex;align-items:center}.bhBuildSlot .compIcon{width:36px!important;height:36px!important;object-fit:contain}.bhSlotText{width:100%;min-width:0}.bhSlotText small{display:block;color:#899ab3;font-size:7px;font-weight:900;letter-spacing:.5px}.bhSlotText b{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;font-size:9px;line-height:1.15;margin-top:2px}.bhSlotText em{display:block;font-style:normal;color:#ffd34e;font-size:8px;font-weight:950;margin-top:4px}.bhStatus{margin-top:auto;font-size:7px;font-weight:950;padding:5px;border-radius:7px;line-height:1.05}.bhMetaGood{color:#9ff0c6;background:rgba(97,230,167,.09);border:1px solid #3f8067}.bhMetaOwned{color:#ffd95b;background:rgba(255,211,78,.08);border:1px solid #66572b}.bhMetaMissing{color:#ffcf76;background:rgba(255,170,60,.08);border:1px solid #6e5433}.bhEquipped{color:#9ff0c6;background:#172d28;border:1px solid #396f5c}.bhOwned{color:#9ecbff;background:#182b45;border:1px solid #41678f}.bhMissing{color:#ff9daa;background:#33242d;border:1px solid #70434f}.bhUnknown{color:#aebbd0;background:#202e46;border:1px solid #405274}.bhPending{color:#aebbd0;background:#1b273c;border:1px dashed #617494}.bhSlotMetaEquipped{border-color:#4e9277;background:linear-gradient(180deg,rgba(97,230,167,.08),#16243a)}.bhSlotMetaOwned{border-color:#8b7830}.bhSlotMetaMissing{border-color:#8a6537}.bhSlotPending{border-style:dashed;border-color:#566983;background:#141f31}.bhSlotEquipped{border-color:#3d745f}.bhSlotOwned{border-color:#41678f}.bhSlotMissing{border-color:#70434f}
.bhLegend{display:flex;gap:9px;flex-wrap:wrap;margin-top:11px;color:#8fa0b9;font-size:8px}.bhLegend span{display:flex;align-items:center;gap:4px}.bhLegend i{width:7px;height:7px;border-radius:50%;display:inline-block}.bhLegendMeta{background:#ffd34e}.bhLegendGood{background:#61e6a7}.bhLegendOwn{background:#5fa8ff}.bhLegendMissing{background:#ff687c}.bhLegendUnknown{background:#617494}.bhStatGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.bhStatGrid>div{background:#16243a;border:1px solid #334765;border-radius:11px;padding:9px}.bhStatGrid b{display:block;font-size:17px}.bhStatGrid span{font-size:7px;color:#899ab3;font-weight:900}
.bhModeTabs{display:flex;gap:5px;overflow:auto;padding:2px 0 8px}.bhModeTabs button{white-space:nowrap;border:1px solid #334765;background:#16243a;color:#9eacc1;border-radius:999px;padding:7px 9px;font-size:9px;font-weight:850}.bhModeTabs button.active{color:#ffd34e;border-color:#806d2f;background:rgba(255,211,78,.08)}.bhMetaNumbers{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px}.bhMetaNumbers span{font-size:8px;color:#899ab3;background:#16243a;border:1px solid #334765;border-radius:10px;padding:8px}.bhMetaNumbers b{display:block;font-size:14px;color:#fff}
.bhQuickGuide{background:linear-gradient(145deg,#16233a,#111b2c);border-color:#405274}.bhQuickGuide p{font-size:10px;line-height:1.5;color:#aebbd0}.bhGuideGrid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.bhGuideGrid>div{background:#111d30;border:1px solid #30445f;border-radius:11px;padding:9px}.bhGuideGrid span{display:block;font-size:7px;color:#899ab3;font-weight:900}.bhGuideGrid b{display:block;margin-top:3px;font-size:9px;line-height:1.25}.bhTips{display:grid;gap:6px;margin-top:7px}.bhTips>div{border-left:2px solid #ffd34e;background:rgba(255,211,78,.045);padding:7px 9px}.bhTips b{display:block;font-size:9px}.bhTips span{display:block;font-size:8px;color:#8fa0b9;line-height:1.35;margin-top:2px}
.bhBuffGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.bhBuffie{display:flex;align-items:center;gap:7px;text-align:left;border:1px solid #334765;background:#16243a;color:#fff;border-radius:11px;padding:8px}.bhBuffIcon{width:23px;height:23px;display:grid;place-items:center;border-radius:7px;background:#243653;font-size:11px;font-weight:950}.bhBuffie b{display:block;font-size:8px}.bhBuffie small{display:block;color:#899ab3;font-size:7px;margin-top:2px}.bhBuffOwned{border-color:#3f8067}.bhBuffOwned .bhBuffIcon{color:#9ff0c6;background:#17332b}.bhBuffAvailable{border-color:#49658a}.bhBuffMissing{border-color:#5d3d48}.bhBuffMissing .bhBuffIcon{color:#ff9daa;background:#34232c}
.bhActionRow{display:flex;align-items:center;gap:9px;background:#16243a;border:1px solid #334765;color:#fff;border-radius:12px;padding:10px;margin-top:6px}.bhActionIcon{width:27px;height:27px;border-radius:8px;display:grid;place-items:center;background:#243653;color:#ffd34e;font-weight:950}.bhActionRow b{display:block;font-size:10px}.bhActionRow small{display:block;color:#899ab3;font-size:8px;margin-top:2px;line-height:1.3}.bhEmpty{padding:13px;border:1px dashed #405274;border-radius:13px;background:#141f31}.bhEmpty b{display:block;font-size:10px}.bhEmpty span{display:block;color:#899ab3;font-size:8px;margin-top:3px}
.bhHomeHero{margin:12px 0;padding:18px;border-radius:24px;background:radial-gradient(circle at 100% 0,rgba(255,211,78,.13),transparent 35%),linear-gradient(145deg,#17253e,#0f1829);border:1px solid #3b5377;box-shadow:0 16px 45px rgba(0,0,0,.23)}.bhHomeHero h1{margin:3px 0;font-size:30px}.bhHomeHero p{margin:0;color:#8fa0b9;font-size:10px}.bhHomeStats{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:13px}.bhHomeStats>div{background:rgba(12,23,39,.6);border:1px solid #30445f;border-radius:11px;padding:9px}.bhHomeStats b{display:block;font-size:17px}.bhHomeStats span{font-size:7px;color:#899ab3;font-weight:900}.bhQuickActions{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:10px 0 17px}.bhQuickActions button{background:#16243a;border:1px solid #334765;color:#fff;border-radius:14px;padding:11px 8px;text-align:left}.bhQuickActions button:hover{border-color:#ffd34e}.bhQuickActions b{display:block;font-size:10px}.bhQuickActions span{display:block;color:#899ab3;font-size:8px;margin-top:2px}.bhHomeData{margin-bottom:20px}.bhSyncDot{font-size:8px;color:#9ff0c6}.bhDataGrid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.bhDataGrid span{font-size:8px;color:#899ab3;border:1px solid #334765;background:#16243a;border-radius:10px;padding:8px}.bhDataGrid b{float:right;color:#fff}
.bhBrawlerCard{display:flex;align-items:center;gap:9px;margin:7px 0;padding:10px;border-radius:15px;background:#16243a;border:1px solid #334765;box-shadow:0 7px 20px rgba(0,0,0,.16);cursor:pointer}.bhBrawlerCard:hover{border-color:#566f96;transform:translateY(-1px)}.bhRank{width:25px;min-width:25px;height:25px;display:grid;place-items:center;border-radius:8px;background:#202f47;color:#ffd34e;font-weight:950;font-size:9px}.bhCardPortrait{width:54px;height:54px;border-radius:14px;object-fit:contain;background:#111d30;border:1px solid #30445f}.bhCardMain{min-width:0;flex:1}.bhCardTop{display:flex;justify-content:space-between;gap:6px}.bhCardTop>b{font-size:13px}.bhPower{font-size:8px;color:#9eacc1;border:1px solid #334765;border-radius:7px;padding:3px 5px}.bhCardSub{font-size:8px;color:#899ab3;margin-top:2px}.bhMetricRow{display:grid;grid-template-columns:repeat(4,1fr);gap:3px;margin-top:7px}.bhMetricRow span{background:#111d30;border:1px solid #293c57;border-radius:7px;padding:4px;text-align:center}.bhMetricRow b{display:block;font-size:9px}.bhMetricRow small{display:block;color:#71839c;font-size:6px;font-weight:900}
@media(max-width:430px){.bhBuildGrid{grid-template-columns:repeat(5,64px)}.bhBuildSlot{min-width:64px;min-height:136px}.bhHero h1{font-size:30px}.bhStatGrid{grid-template-columns:repeat(2,1fr)}.bhBuffGrid{grid-template-columns:1fr}.bhGuideGrid{grid-template-columns:1fr}.bhMetricRow{grid-template-columns:repeat(4,1fr)}.bhBrawlerCard{padding:8px}.bhCardPortrait{width:48px;height:48px}}
\`;
const st=document.createElement('style');st.id='bh-ui-v2';st.textContent=css;document.head.appendChild(st);
setTimeout(()=>{try{if(window.P&&window.render)window.render()}catch(e){console.error(e)}},0);
})();